//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForEmployees.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int IdClient { get; set; }
        public string ClientSurname { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientPatronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string SeriyaNumber { get; set; }
        public string WhoIssued { get; set; }
        public int DepartmentCode { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public int IdPlaceOfBirth { get; set; }
    
        public virtual PlaceOfBirth PlaceOfBirth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
