//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForEmployees.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorking
    {
        public int IdWork { get; set; }
        public bool WorkInProcess { get; set; }
        public bool WorkFinished { get; set; }
        public int IdEmployee { get; set; }
        public int IdRequest { get; set; }
        public byte[] Report { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
    }
}
