//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForEmployees.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceOfBirth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceOfBirth()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int IdPlaceOfBirth { get; set; }
        public int IdCountry { get; set; }
        public int IdCity { get; set; }
        public Nullable<int> IdKray { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Country Country { get; set; }
        public virtual Kray Kray { get; set; }
    }
}
