//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForEmployees.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.EmployeeWorking = new HashSet<EmployeeWorking>();
        }
    
        public int IdRequest { get; set; }
        public int IdClient { get; set; }
        public int IdRole { get; set; }
        public string WorkDescription { get; set; }
        public string CadastralNumber { get; set; }
        public string NumberCapitalConstruction { get; set; }
        public Nullable<int> IdAddress { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeWorking> EmployeeWorking { get; set; }
        public virtual EstateAddress EstateAddress { get; set; }
        public virtual Role Role { get; set; }
    }
}
